# Generated by Django 5.0.2 on 2024-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('starred', models.BooleanField(default=False)),
                ('Degree_of_Importance', models.CharField(choices=[('H', 'High'), ('M', 'Mediume'), ('L', 'Low')], default='M', max_length=1)),
            ],
        ),
    ]
