# Generated by Django 5.0.2 on 2024-02-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_uplodedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='home.todo')),
            ],
        ),
    ]
