# Generated by Django 5.0.2 on 2024-02-21 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='home.board'),
        ),
    ]
