# Generated by Django 5.0.2 on 2024-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_board_todo_todo_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('Todo', 'todo'), ('Doing', 'doing'), ('Done', 'Done'), ('Add_list', 'add_list')], default='Doing', max_length=8),
        ),
    ]
