# Generated by Django 5.0.2 on 2024-02-21 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_todo_started_alter_board_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hexadecimal code.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
