# Generated by Django 5.0.2 on 2024-02-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_todo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
